services:
  - type: web
    name: shareplate
    runtime: node
    plan: free
    buildCommand: npm ci && VITE_Backend_URL=$RENDER_EXTERNAL_URL npm run build
    startCommand: npm start
    healthCheckPath: /api/donation/test
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        fromService:
          name: shareplate
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_EMAIL
        sync: false
      - key: CLOUDFLARE_R2_ENDPOINT
        sync: false
      - key: CLOUDFLARE_R2_ACCESS_KEY
        sync: false
      - key: CLOUDFLARE_R2_SECRET_KEY
        sync: false
      - key: CLOUDFLARE_R2_BUCKET_NAME
        sync: false
      - key: CLOUDFLARE_R2_PUBLIC_URL
        sync: false
      - key: VITE_Backend_URL
        fromService:
          name: shareplate
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false
      - key: VITE_GOOGLE_MAPS_API_KEY
        sync: false
